
services:
  coincidence_system:
    build:
      context: ../SNEWS_Coincidence_System
      dockerfile: ../SNEWS_Coincidence_System/Dockerfile
    container_name: coincidence_system
    environment:
      - REMOVE_FIGURES_AFTER=7
    ports:
      - "5001:5000"

  publishing_tools_subscriber:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: publishing_tools_subscriber
    command: snews_pt subscribe --outputfolder /app/output -p /app/snews_pt/auxiliary/custom_script.py --firedrill
    ports:
      - "5002:5000"
    depends_on:
      - coincidence_system

  publishing_tools_publisher:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: publishing_tools_publisher
    ports:
      - "5003:5000"
    depends_on:
      - coincidence_system
#      - publishing_tools_subscriber
